application: postrwall
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /style
  static_dir: static/style
- url: /images
  static_dir: static/images
- url: /javascript
  static_dir: static/javascript
- url: /design
  static_dir: static/design
- url: /content
  static_dir: static/content
- url: /Admin/.*
  script: AdminRouter.app2
- url: /.*
  script: Router.app

libraries :
- name: webapp2
  version: latest